### ISSUE TITLE
Missing or not working attributes.

### ISSUE THREAD

**Issue by badge234** [dnkorpushov/ebookmeta#10]
Hi, 

I tried your library but I get an error message when I try: "meta.tags attribute"
The error says that metadata object has no attribute 'tags'

Also, I have the "Publisher" attribute in my epubs that contain data but when I try to read the "meta.publish_info.publisher" attribute, I get an empty value.

Finally, I could not find a "Type" attribute that corresponds to the type of book (ie. Fantasy, sci-fi, romance, adventure, etc.)
Do you not have this tag for your epubs?

Thanks.

Paul

**Comment by dnkorpushov** [comment]
Use meta.tag_list instead meta.tags. (I corrected the bug in guide).
meta.publish_info.* data structure used only for fb2 file format, not epub.
Attribute "Type" not yet supported.

**Comment by badge234** [comment]
Hello.

Thank you for your reply. I see several of my epub files with the publisher name in the metadata usually “Publisher : abcd”. Same with the “genre” or “type” of book. Since that information seems to be available within the epub metadata, do you have any plans to add those to your ebookmeta librairy?

Thanks again.

Paul

De : Dmitrii ***@***.***>
Envoyé : 24 octobre 2022 08:42
À : dnkorpushov/ebookmeta ***@***.***>
Cc : badge234 ***@***.***>; Author ***@***.***>
Objet : Re: [dnkorpushov/ebookmeta] Missing or not working attributes. (Issue #10)


Use meta.tag_list instead meta.tags. (I corrected the bug in guide).
meta.publish_info.* data structure used only for fb2 file format, not epub.
Attribyte "Type" not yet supported.
