### ISSUE TITLE
set_author_list_from_string creates invalid epub2

### ISSUE THREAD

**Issue by titusz** [dnkorpushov/ebookmeta#13]
When using `meta.set_author_list_from_string` with en EPUB2 file it creates an invalid EPUB.

The metadata entry looks like this:
`<dc:creator role="aut">The Creator</dc:creator>`

The epubcheck error message is:
`Error while parsing file: attribute "role" not allowed here; expected attribute "id", "opf:file-as", "opf:role" or "xml:lang"`

**Comment by dnkorpushov** [comment]
Check version 1.2.11
