### ISSUE TITLE
problem with %20 (blank) in filenames 

### ISSUE THREAD

**Issue by docjc** [dnkorpushov/ebookmeta#6]
Hi,
Great lib - helps alot (also for understanding)
I'm always gettig error msg using "ebookmeta.get_metadata" if the epubs have cover images containing blanks in the name which are changed to %20 for example by Sigil. When I change the name of the jpg to a name without blanks the errors are gone.
Have a nice day
Jü

**Comment by dnkorpushov** [comment]
@docjc 
Check 1.2.8 release to resolve it

**Comment by docjc** [comment]
Hi,
thank you - problem solved
Jü
