### ISSUE TITLE
Renaming authors with commas in names.

### ISSUE THREAD

**Issue by rariera** [dnkorpushov/ebookmeta#7]
Hey, I'm writing a utility to automatically clean up the author names of a bunch of epubs into the format 'last_name, first_name', for example "Sanderson, Brandon". I was keen to use this utility for it, but found that I can't use the current set_author_list_from_string method since it'll chop the author names in half at the comma.

Would you be able to add methods for individually adding/removing author names so I can use this aspect? Thanks!

**Comment by dnkorpushov** [comment]
@rariera, You can read/write author list directly using author_list attribute in Metadata class like this:

```python
import ebookmeta

# Get metadata form file
meta = ebookmeta.get_metadata('book.epub')
print(meta.author_list)

# Create new authors list
new_author_list = []
new_author_list.append('Azimov, Isaac')
new_author_list.append('Bradbury, Ray')

# Change author list in metadata
meta.author_list = new_author_list

# Save new metadata into file
ebookmeta.set_metadata('book.epub', meta)

# Check result
meta = ebookmeta.get_metadata('book.epub')
print(meta.author_list)
```
