### ISSUE TITLE
Series in epub3

### ISSUE THREAD

**Issue by docjc** [dnkorpushov/ebookmeta#8]
hi,
as you may know the series and  series number are not available in epub3 only in epub2. This is now called belongs-to-collection and there are 2 (or more) subs: collectien-type (will be series) and group-position (will be series index)). As far as I understand this is not implemented yet in ebookmeta. Do you have any idea to implement this????? Would be nice to have.

Jü

**Comment by dnkorpushov** [comment]
@docjc 
 Now ebookmeta use series tags for epub2 and epub3, which are generated by Calibre
  - calibre:series
  - calibre:series_index

I will plan this feature in the next release.

**Comment by docjc** [comment]
To understand correctly:  the epub2 tags can also be used in epub3 files????

**Comment by dnkorpushov** [comment]
The epub2 spec does not contain metadata for specifying a book series.
calibre:series, calibre:series_index not a part of epub2 spec. These are custom metadata tags, supported by Calibre. 
Both epub spec (2 and 3) allow to use custom metadata.

**Comment by docjc** [comment]
ok - thanks for the explanation - I'm just starting programming in python to sort my epubs ;)
